name: Vulnerability test for EC-CUBE
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'
jobs:
  codeception:
    name: Codeception
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        eccube: [ 4.2, 4.2.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.4

      - name: Clone EC-CUBE
        run: git clone https://github.com/EC-CUBE/ec-cube.git

      - name: composer install
        working-directory: ec-cube
        run: composer install --no-interaction -o --apcu-autoloader
        shell: bash

      - name: Packaging EC-CUBE
        run: ./ec-cube/package.sh

      - name: Build Container
        working-directory: ec-cube
        run: |
          docker build -t ec-cube .

      - name: Container Run
        working-directory: ec-cube
        run: |
          docker run -e APP_ENV=prod -e APP_DEBUG=0 -e DATABASE_URL="sqlite:///var/eccube.db" -e DATABASE_SERVER_VERSION=3 --rm -d -p 8080:80 --name eccube ec-cube
          echo -n $(docker inspect -f {{.State.Health.Status}} eccube)
          until [ $(docker inspect -f {{.State.Health.Status}} eccube) != "starting" ]; do
            echo -n .
            sleep 10;
          done;
          docker inspect -f {{.State.Health.Status}} eccube
          docker cp ../eccube.tar.gz eccube:/tmp/
          docker exec -w /tmp eccube bash -c "rm -rf /var/www/html; tar xf /tmp/eccube.tar.gz -C /var/www; mv /var/www/ec-cube /var/www/html; chown -R www-data: /var/www/html"
          docker exec -u www-data eccube bin/console eccube:install -n
          docker exec -u www-data eccube bash -c 'for code in Api42 Coupon42 MailMagazine42 ProductReview42 Recommend42 RelatedProduct42 SalesReport42 Securitychecker42 SiteKit42; do bin/console eccube:plugin:enable --code $code; done'

      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Run chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          echo ">>> Started chrome-driver"
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      - name: Run codeception
        run: php vendor/bin/codecept run --steps

      - name: Upload evidence
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.eccube }}-evidence
          path: tests/_output/
